# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Togo Parliamentary Monitoring
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find information about politicians in Togo
baseurl: "/togo-pmo" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ''
exclude: [Gemfile, Gemfile.lock, README.md, vendor]

# Build settings
markdown: kramdown

# EveryPolitician data configuration:
everypolitician:
 sources:
   - 'https://cdn.rawgit.com/everypolitician/everypolitician-data/c6e0e76/data/Togo/Assembly/ep-popolo-v1.0.json'

collections:
 people:
  output: true
  permalink: '/mps/:path/'
 events:
  output: true
  permalink: '/terms/:path/'
 areas:
  output: true
  permalink: '/constituency/:path/'
